server:
  port: 8062

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    discovery:
      client:
        registration:
          eureka:
            enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://103.168.18.176:8060/eureka/