spring:
  data:
    mongodb:
      uri: mongodb+srv://sharad-chavhan:sharad-chavdar-vishranti@chavdar-vishranti.t7dvk.mongodb.net/chavdar-vishranti?retryWrites=true&w=majority&ssl=true


jwt:
  secret: your-256-bit-base64-encoded-key
  expiration: 3600000

