server:
  port: 8063

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chavdar-vishranti
  cloud:
    config:
      uri: http://localhost:8061   

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/

  config:
    import: optional:configserver:http://localhost:8061
