spring:
  config:
    activate:
      on-profile: dev
  discovery:
    client:
      registration:
        eureka:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/