server:
  port: 8062

spring:
  cloud:
    gateway:
      routes:
        - id: cv-auth-service
          uri: lb://cv-auth-service
          predicates:
            - Path=/cv-auth/**
          # filters:
          #   - StripPrefix=0

        - id: cv-admin-microservice
          uri: lb://cv-admin-microservice
          predicates:
            - Path=/cv-admin/**

        - id: cv-owner-microservice
          uri: lb://cv-owner-microservice
          predicates:
            - Path=/cv-owner/**

        - id: cv-hotel-microservice
          uri: lb://cv-hotel-microservice
          predicates:
            - Path=/cv-hotel/**