server:
  port: 8063

spring:
  config:
    activate:
      on-profile: dev
  discovery:
      client:
        registration:
          eureka:
            enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chavdar-vishranti
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/

  
