eureka:
  cloud:
    gateway:
      routes:
        - id: cv-auth-service
          uri: http://localhost:8063
          predicates:
            - Path=/auth/**
        
  # Keystore properties for HTTPS
  # ssl:
  #   key-store: classpath:keystore.p12
  #   key-store-password: sharad
  #   key-store-type: PKCS12
  #   key-alias: myapp


  
