spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb+srv://sharad-chavhan:sharad-chavdar-vishranti@chavdar-vishranti.t7dvk.mongodb.net/chavdar-vishranti?retryWrites=true&w=majority&ssl=true
server:
  port: 8063

eureka:
  client:
    service-url:
      defaultZone: http://103.168.18.176:8060/eureka/

  config:
    import: optional:configserver:http://103.168.18.176:8061
