spring:
  config:
    activate:
      on-profile: dev
  discovery:
    client:
      registration:
        eureka:
          enabled: true
  data:
    mongodb:
      # uri: mongodb+srv://sharad-chavhan:sharad-chavdar-vishranti@chavdar-vishranti.t7dvk.mongodb.net/chavdar-vishranti?retryWrites=true&w=majority&ssl=true
      uri:  mongodb+srv://2124programmer:cv-dev-db@cv-dev.3n3m5.mongodb.net/?retryWrites=true&w=majority&appName=cv-dev
  # data:
  #   mongodb:
  #     host: localhost
  #     port: 27017
  #     database: chavdar-vishranti

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/
